// <auto-generated />
namespace CvBuilder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixPK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixPK));
        
        string IMigrationMetadata.Id
        {
            get { return "202109090345008_fixPK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
